[app]
app_name = 'doak-fs'
version = '1.0.2'
debug = true
time_zone = 'Asia/Hong_Kong'
log_file = './fs-log.log'
log_level = 'error'
assets = '/static'
# 文件预览主题
code_theme = "ambiance"

[server]
address = ':1323'
csrf_token_length = 32
csrf_context_key = 'fs_csrf'
csrf_cookie_name = '_fs_csrf'
csrf_cookie_path = '/'
csrf_cookie_maxage = 86400

[file]
path = './'
driver = 'local'

[user]
names = ['admin:$2a$10$EnHCul2nbg0ZmvL0OEdoOOC4hkzniHO8zFS/vlGVSKYGlMX53qZNu']

[session]
secret = 'secret'
key = 'session'
path = '/'
max_age = 604800 # 86400 * 7
http_only = true
